# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fast-deep-rnn',
                'doc_host': 'https://Hacker1337.github.io',
                'git_url': 'https://github.com/Hacker1337/fast-deep-rnn',
                'lib_path': 'fast_deep_rnn'},
  'syms': {'fast_deep_rnn.core': {'fast_deep_rnn.core.foo': ('core.html#foo', 'fast_deep_rnn/core.py')}}}
